version: "3.9"

services:
  api:
    build: .
    container_name: resume_matcher_web
    command: uvicorn api.main_api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data/raw_resumes:/app/data/raw_resumes
      - ./database:/app/database
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
